# Generated by Django 5.1.6 on 2025-02-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_coaches_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coaches',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
