# Generated by Django 5.1.6 on 2025-02-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_coaches_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coaches',
            options={'permissions': [('can_access_coach_endpoint', 'Can access coach endpoint')]},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_access_student_endpoint', 'Can access student endpoint')]},
        ),
    ]
