# Generated by Django 5.1.6 on 2025-02-17 15:41

import homeworks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkpicture',
            name='image',
            field=models.ImageField(upload_to=homeworks.models.homework_picture_upload_to),
        ),
    ]
