# Generated by Django 5.1.6 on 2025-02-18 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_alter_homeworkpicture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='score',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='homeworkpicture',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
