# Generated by Django 5.1.6 on 2025-02-18 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_homework_score_homeworkpicture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
