# Generated by Django 5.1.6 on 2025-02-18 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0005_alter_homework_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
