# Generated by Django 5.1.6 on 2025-02-19 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0006_alter_homework_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='score_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
